import {
  Sparkles, Compass, Eye, Flame, Moon, HeartHandshake, Infinity as InfinityIcon,
  Sun, Star, Target, Users, Zap, Heart, Coins, Briefcase, Brain,
  Leaf, Sprout, Building2, KeyRound, BookOpen, Scale, TrendingUp, Waves,
  Shield, Handshake, Landmark, Activity, Sparkle, Clock, Feather, Gem,
  type LucideIcon,
} from "lucide-react";


export type PersuasivePillar = { icon: LucideIcon; title: string; desc: string };
export type PersuasiveTestimonial = { name: string; text: string; rating: number };
export type PersuasiveFaq = { q: string; a: string };

export type PersuasiveCopy = {
  eyebrow: string;                     // pill no topo do hero
  heroHeadline: string;                // linha 1 do H1
  heroHeadlineAccent: string;          // linha 2 dourada
  heroSub: string;                     // parágrafo do hero (pode conter <strong>…</strong>)
  heroBullets: string[];               // até 3 bullets
  socialProofLabel: string;            // ex.: "4.9 · +2.500 almas"
  urgencyBar: string;
  livePurchase: string;                // ex.: "37 pessoas compraram nas últimas 24h"
  painEyebrow: string;
  painHeadline: string;                // pode conter <em>…</em>
  painBody: string;                    // pode conter <strong>…</strong>
  pillarsEyebrow: string;
  pillarsHeadline: string;
  pillars: PersuasivePillar[];
  testimonialsEyebrow: string;
  testimonialsHeadline: string;
  testimonials: PersuasiveTestimonial[];
  guaranteeTitle: string;
  guaranteeBody: string;               // pode conter <strong>…</strong>
  faqEyebrow: string;
  faqHeadline: string;
  faqs: PersuasiveFaq[];
  finalEyebrow: string;
  finalHeadline: string;               // pode conter <em>…</em> e \n
  finalBody: string;
  dialogTitle: string;
  dialogDesc: string;
};

const commonHow = [
  { num: "01", title: "Preencha seus dados", desc: "Nome e informações necessárias. Leva 60 segundos." },
  { num: "02", title: "Pagamento seguro", desc: "Cartão, Pix ou boleto pelo Mercado Pago. Aprovação imediata." },
  { num: "03", title: "Receba sua leitura", desc: "PDF premium no e-mail e WhatsApp em minutos." },
];

export const COMMON_HOW = commonHow;

export const PERSUASIVE_COPY: Record<string, PersuasiveCopy> = {
  "mapa-espiritual": {
    eyebrow: "Leitura de Alma · Nível Avançado",
    heroHeadline: "A sua alma tem uma missão.",
    heroHeadlineAccent: "E ela já foi escrita.",
    heroSub: "Descubra o mapa oculto que sua alma trouxe pra esta encarnação: <strong>karma, mediunidade, feridas ancestrais e os portais exatos do seu despertar</strong> nos próximos 12 meses.",
    heroBullets: [
      "Por que certas dores se repetem — e como quebrar o ciclo",
      "Os dons espirituais que você tem (mas ainda não ativou)",
      "As datas exatas dos seus próximos saltos de consciência",
    ],
    socialProofLabel: "4.9 · +2.500 almas",
    urgencyBar: "Oferta de despertar — vagas limitadas nesta semana cósmica",
    livePurchase: "37 pessoas compraram nas últimas 24h",
    painEyebrow: "Se você chegou até aqui…",
    painHeadline: "Algo dentro de você sabe que <em>veio pra mais</em>.",
    painBody: "Você sente que está no lugar errado. Que existe um propósito maior. Que sonhos, sincronicidades e intuições estão te chamando — mas sem um mapa, tudo vira ruído. <strong>É hora de ver com clareza o que sua alma veio fazer aqui.</strong>",
    pillarsEyebrow: "O que você vai receber",
    pillarsHeadline: "6 revelações que mudam sua rota",
    pillars: [
      { icon: Compass, title: "Missão Kármica", desc: "O propósito exato pelo qual sua alma escolheu esta encarnação — e o que você precisa concluir." },
      { icon: Eye, title: "Dons Mediúnicos", desc: "Sensibilidades ocultas que já se manifestam em você e como ativá-las com segurança." },
      { icon: Flame, title: "Feridas Ancestrais", desc: "Padrões herdados que travam sua evolução — e o ritual para dissolver cada um." },
      { icon: Moon, title: "Portais de Despertar", desc: "Janelas cósmicas específicas dos seus próximos 12 meses para saltos espirituais." },
      { icon: HeartHandshake, title: "Práticas Alinhadas", desc: "Meditação, mantras e rituais escolhidos a dedo para o SEU mapa — não genéricos." },
      { icon: InfinityIcon, title: "Ciclos Evolutivos", desc: "Onde você está na roda da alma e o próximo passo pra sair do platô espiritual." },
    ],
    testimonialsEyebrow: "Provas de despertar",
    testimonialsHeadline: "Quem leu, nunca mais foi o mesmo",
    testimonials: [
      { name: "Camila R.", text: "Chorei lendo. Coisas que eu sentia há anos ganharam nome. Nunca vi algo tão preciso.", rating: 5 },
      { name: "Rafael M.", text: "A missão kármica bateu em cheio. Mudei decisões importantes depois dessa leitura.", rating: 5 },
      { name: "Juliana P.", text: "Achei que fosse mais um relatório genérico. É o oposto: parece feito só pra mim.", rating: 5 },
    ],
    guaranteeTitle: "Garantia incondicional de 7 dias",
    guaranteeBody: "Leia. Sinta. Aplique. Se em 7 dias você não sentir que este mapa mudou sua forma de enxergar sua alma, devolvemos <strong>100% do seu dinheiro</strong>. Sem perguntas, sem burocracia. O risco é todo nosso.",
    faqEyebrow: "Perguntas frequentes",
    faqHeadline: "Ainda em dúvida?",
    faqs: [
      { q: "Em quanto tempo recebo?", a: "Em poucos minutos após o pagamento aprovado. Você recebe no e-mail e no WhatsApp." },
      { q: "Preciso saber a hora exata do nascimento?", a: "Ajuda muito, mas se não souber, geramos com aproximação. Basta informar." },
      { q: "É seguro? E se eu não gostar?", a: "Garantia incondicional de 7 dias. Não gostou? Devolvemos 100% sem perguntas." },
      { q: "Como é diferente de um mapa astral comum?", a: "É focado 100% na jornada da alma: karma, mediunidade e despertar — não em previsões banais." },
    ],
    finalEyebrow: "Sua alma está chamando",
    finalHeadline: "Ou você continua adivinhando.\nOu você <em>finalmente vê</em>.",
    finalBody: "Menos que o preço de um jantar. Uma revelação que pode reorientar os próximos 10 anos da sua vida.",
    dialogTitle: "Dados para sua leitura de alma",
    dialogDesc: "Preencha com atenção — a precisão dos dados torna a leitura mais profunda. Após o pagamento criamos sua conta e enviamos o PDF por e-mail.",
  },

  "mapa-astral-completo": {
    eyebrow: "Mapa Astral · Análise Completa",
    heroHeadline: "Você não é aleatório.",
    heroHeadlineAccent: "Você foi escrito nas estrelas.",
    heroSub: "Um mapa astral profissional que revela <strong>a arquitetura invisível da sua personalidade, relacionamentos e propósito</strong> — decifrado pelos astros do dia exato em que você nasceu.",
    heroBullets: [
      "Por que você age assim (e por que os outros não te entendem)",
      "Os talentos escondidos no seu mapa que ninguém te mostrou",
      "O que os planetas dizem sobre amor, dinheiro e carreira em você",
    ],
    socialProofLabel: "4.9 · +5.000 mapas gerados",
    urgencyBar: "Análise completa — desconto especial por tempo limitado",
    livePurchase: "62 pessoas geraram o mapa nas últimas 24h",
    painEyebrow: "Cansou dos horóscopos genéricos?",
    painHeadline: "Signo solar é só <em>1%</em> do que você é.",
    painBody: "Sol, Lua, Ascendente, Vênus, Marte, casas, aspectos — tudo isso forma quem você realmente é. Ler só o signo é como julgar um livro pela capa. <strong>Está na hora de ler o livro inteiro.</strong>",
    pillarsEyebrow: "O que você vai descobrir",
    pillarsHeadline: "10+ áreas mapeadas em detalhe",
    pillars: [
      { icon: Sun, title: "Sol, Lua e Ascendente", desc: "Sua essência, emoções e a máscara que você mostra ao mundo — decifrados com precisão." },
      { icon: Heart, title: "Amor e Relacionamentos", desc: "Vênus, Marte e Casa 7: como você ama, o que atrai e o que sabota seus vínculos." },
      { icon: Briefcase, title: "Carreira e Propósito", desc: "Meio-do-Céu, Casa 10 e Saturno mostrando onde você brilha profissionalmente." },
      { icon: Brain, title: "Mente e Comunicação", desc: "Mercúrio revelando como você pensa, aprende e se expressa — e como usar isso a favor." },
      { icon: Target, title: "Talentos e Dons", desc: "Aspectos harmônicos que mostram habilidades naturais que você ainda não explorou." },
      { icon: Star, title: "Trânsitos do Ano", desc: "Os movimentos planetários que mais vão impactar sua vida nos próximos 12 meses." },
    ],
    testimonialsEyebrow: "Provas nas estrelas",
    testimonialsHeadline: "Depoimentos reais de quem se encontrou",
    testimonials: [
      { name: "Marina S.", text: "Nunca imaginei tanta profundidade. Entendi por que sempre me sentia deslocada — e finalmente aceitei quem sou.", rating: 5 },
      { name: "Bruno T.", text: "Impressionante. O que dizia sobre carreira previu exatamente a mudança que fiz meses depois.", rating: 5 },
      { name: "Larissa F.", text: "Comprei por curiosidade. Saí com um mapa que uso toda semana pra tomar decisões.", rating: 5 },
    ],
    guaranteeTitle: "Garantia total de 7 dias",
    guaranteeBody: "Leia todo o mapa. Se não sentir que valeu cada centavo, devolvemos <strong>100% do seu investimento</strong>. Sem perguntas. Sem letras miúdas. O risco é nosso.",
    faqEyebrow: "Perguntas frequentes",
    faqHeadline: "Antes de você decidir",
    faqs: [
      { q: "Em quanto tempo recebo?", a: "Poucos minutos após a aprovação do pagamento. Chega no e-mail e no WhatsApp." },
      { q: "Preciso da hora exata do nascimento?", a: "Sim, é o ideal — calcula o Ascendente e as casas com precisão. Se não souber, geramos com aproximação e você pode ajustar depois." },
      { q: "É diferente de um horóscopo comum?", a: "Totalmente. Horóscopo lê só o Sol. Aqui você recebe 10+ camadas: Sol, Lua, Ascendente, Vênus, Marte, casas, aspectos e trânsitos." },
      { q: "Serve pra quem não conhece astrologia?", a: "Perfeito pra você. O relatório é escrito em linguagem clara, sem jargão — como um mentor explicando." },
    ],
    finalEyebrow: "As estrelas já responderam",
    finalHeadline: "Você continua chutando.\nOu <em>enfim entende</em>.",
    finalBody: "O mapa astral mais completo do mercado, ao preço de um livro. Um retrato preciso de quem você é — pra vida toda.",
    dialogTitle: "Dados para seu mapa astral",
    dialogDesc: "A precisão da hora e local de nascimento define a precisão do mapa. Após o pagamento criamos sua conta e enviamos o PDF por e-mail.",
  },

  "mapa-do-amor": {
    eyebrow: "Mapa do Amor · Leitura Íntima",
    heroHeadline: "Seu coração fala uma língua.",
    heroHeadlineAccent: "Chegou a hora de traduzi-la.",
    heroSub: "Descubra <strong>como você ama, o que te atrai de verdade e os padrões invisíveis que sabotam seus relacionamentos</strong> — decifrados pelos astros do amor no seu mapa.",
    heroBullets: [
      "Por que você atrai sempre o mesmo tipo de pessoa",
      "Sua verdadeira linguagem do amor (não é o que você pensa)",
      "O que Vênus e Marte revelam sobre seu desejo e afeto",
    ],
    socialProofLabel: "4.9 · +3.200 corações lidos",
    urgencyBar: "Leitura do amor — condição especial ativa esta semana",
    livePurchase: "48 pessoas descobriram nas últimas 24h",
    painEyebrow: "Se o amor parece um enigma…",
    painHeadline: "Talvez você esteja amando <em>no idioma errado</em>.",
    painBody: "Você se entrega, mas se sente incompreendida. Escolhe pessoas parecidas e o ciclo se repete. Não é falta de sorte — é <strong>um padrão inscrito no seu mapa que ninguém te mostrou como ler</strong>.",
    pillarsEyebrow: "O que você vai desvendar",
    pillarsHeadline: "6 camadas do seu amor",
    pillars: [
      { icon: Heart, title: "Sua Vênus", desc: "Como você ama, o que te encanta e o que te faz sentir amada de verdade." },
      { icon: Flame, title: "Seu Marte", desc: "Desejo, paixão e a forma como você conquista — e como aparece nas brigas." },
      { icon: HeartHandshake, title: "Casa 7 — Parcerias", desc: "O perfil da pessoa que seu mapa atrai (e do parceiro ideal pra sua evolução)." },
      { icon: Moon, title: "Sua Lua no Amor", desc: "Do que sua alma precisa emocionalmente pra se sentir segura em um vínculo." },
      { icon: Eye, title: "Padrões que Se Repetem", desc: "As feridas de infância que você projeta no amor — e como quebrar o loop." },
      { icon: Star, title: "Janelas Astrais do Amor", desc: "Os melhores momentos dos próximos 12 meses pra encontros, DR e decisões." },
    ],
    testimonialsEyebrow: "Depoimentos de coração aberto",
    testimonialsHeadline: "Elas leram e o amor mudou",
    testimonials: [
      { name: "Beatriz L.", text: "Chorei reconhecendo cada padrão. Terminei um ciclo tóxico depois dessa leitura.", rating: 5 },
      { name: "Fernanda G.", text: "Meu marido leu comigo. Nunca conversamos tão fundo sobre o que a gente precisa.", rating: 5 },
      { name: "Aline C.", text: "Descobri por que me apaixono pelo mesmo perfil sempre. Impossível não se ver ali.", rating: 5 },
    ],
    guaranteeTitle: "Garantia de 7 dias — sem risco",
    guaranteeBody: "Leia com calma. Se não sentir que a leitura tocou algo verdadeiro em você, devolvemos <strong>100% do valor</strong>. Simples assim.",
    faqEyebrow: "Perguntas frequentes",
    faqHeadline: "Antes de abrir seu coração",
    faqs: [
      { q: "Em quanto tempo recebo?", a: "Em poucos minutos após o pagamento aprovado. Chega no seu e-mail e WhatsApp." },
      { q: "Preciso da hora exata do nascimento?", a: "Sim, é o ideal pra ler Casa 7 e Vênus com precisão. Se não souber, geramos com aproximação." },
      { q: "Serve pra quem está solteira?", a: "Sim — talvez seja o momento mais importante pra ler. Você entende o padrão antes de repeti-lo." },
      { q: "É diferente do mapa astral comum?", a: "Aqui o foco é só amor: Vênus, Marte, Casa 5, Casa 7, Lua e trânsitos afetivos. Aprofundado nesse tema." },
    ],
    finalEyebrow: "O amor está esperando você entender",
    finalHeadline: "Ou você repete o padrão.\nOu você <em>finalmente escolhe</em>.",
    finalBody: "Menos que um jantar romântico. Uma leitura que muda como você ama pelos próximos anos.",
    dialogTitle: "Dados para sua leitura do amor",
    dialogDesc: "A precisão dos dados aprofunda a leitura. Após o pagamento criamos sua conta e enviamos o PDF por e-mail.",
  },

  "tarot-dos-caminhos": {
    eyebrow: "Tarot dos Caminhos · Leitura Guiada",
    heroHeadline: "Você já sabe a resposta.",
    heroHeadlineAccent: "As cartas só a colocam à luz.",
    heroSub: "Uma tiragem profunda dos <strong>Arcanos Maiores e Menores</strong> pra iluminar a decisão que você vem adiando — carreira, amor, mudança ou virada.",
    heroBullets: [
      "A energia que domina sua vida agora",
      "O que precisa ser encerrado pra o novo entrar",
      "O caminho mais alinhado com sua alma neste ciclo",
    ],
    socialProofLabel: "4.9 · +4.100 tiragens",
    urgencyBar: "Tiragem completa — oferta ativa por tempo limitado",
    livePurchase: "52 pessoas consultaram nas últimas 24h",
    painEyebrow: "Se você está num impasse…",
    painHeadline: "Não é indecisão. É <em>falta de espelho</em>.",
    painBody: "Você pesa prós e contras, escuta todo mundo, e a resposta não vem. É porque a mente racional não alcança o que a alma já decidiu. <strong>O tarot devolve o espelho que faltava.</strong>",
    pillarsEyebrow: "O que sua tiragem revela",
    pillarsHeadline: "6 cartas que reorganizam sua vida",
    pillars: [
      { icon: KeyRound, title: "Situação atual", desc: "A energia real que rege o momento — muitas vezes diferente do que aparenta." },
      { icon: Eye, title: "O que está oculto", desc: "Forças invisíveis atuando por trás dos acontecimentos." },
      { icon: Flame, title: "O que soltar", desc: "Padrões, pessoas ou crenças que estão travando o próximo passo." },
      { icon: Compass, title: "O caminho ideal", desc: "A direção mais alinhada com sua evolução — não a mais óbvia." },
      { icon: Star, title: "Resultado provável", desc: "Pra onde a trajetória atual leva se nada mudar." },
      { icon: Sparkle, title: "Conselho dos Arcanos", desc: "A mensagem-chave que vai orientar suas próximas escolhas." },
    ],
    testimonialsEyebrow: "Provas dos Arcanos",
    testimonialsHeadline: "Quem tirou, agradeceu",
    testimonials: [
      { name: "Diego P.", text: "Assustadoramente preciso. A carta do resultado bateu com o que aconteceu 3 meses depois.", rating: 5 },
      { name: "Priscila M.", text: "Tomei a decisão que estava adiando há um ano. Nunca vou esquecer essa leitura.", rating: 5 },
      { name: "Rita A.", text: "Não é 'previsão'. É clareza. Saí com uma direção que não tinha ideia por onde começar.", rating: 5 },
    ],
    guaranteeTitle: "Garantia de 7 dias",
    guaranteeBody: "Se a leitura não te trouxer clareza real, devolvemos <strong>100% do valor</strong> — sem perguntas.",
    faqEyebrow: "Perguntas frequentes",
    faqHeadline: "Antes de puxar a carta",
    faqs: [
      { q: "Como escolho o tema da leitura?", a: "Você indica no formulário: amor, carreira, decisão específica ou visão geral do momento." },
      { q: "Em quanto tempo recebo?", a: "Poucos minutos após o pagamento. Chega no e-mail e WhatsApp." },
      { q: "Preciso saber de tarot?", a: "Não. A leitura é escrita em linguagem clara, com o significado de cada carta explicado." },
      { q: "Serve pra decisão específica?", a: "Sim — quanto mais claro o tema, mais direta a leitura. Você pode escrever a pergunta." },
    ],
    finalEyebrow: "As cartas já foram embaralhadas",
    finalHeadline: "Ou você segue no impasse.\nOu você <em>vira a carta</em>.",
    finalBody: "Menos que o preço de um livro. Uma leitura que devolve o comando pra sua mão.",
    dialogTitle: "Dados para sua tiragem",
    dialogDesc: "Preencha e escreva o tema da sua consulta. Após o pagamento criamos sua conta e enviamos o PDF por e-mail.",
  },

  "previsao-anual": {
    eyebrow: "Previsão Anual · Mapa dos 12 Meses",
    heroHeadline: "Os próximos 12 meses",
    heroHeadlineAccent: "já estão desenhados nas estrelas.",
    heroSub: "Um <strong>calendário astrológico personalizado</strong> mês a mês, com os trânsitos que vão marcar seu amor, carreira, dinheiro e evolução no ano.",
    heroBullets: [
      "Os melhores meses pra decidir, arriscar ou recuar",
      "Trânsitos de Júpiter, Saturno e Urano no SEU mapa",
      "Aviso antecipado de retrógrados e eclipses que te afetam",
    ],
    socialProofLabel: "4.9 · +3.800 previsões geradas",
    urgencyBar: "Planejamento do ano — condição especial ativa",
    livePurchase: "44 pessoas planejaram nas últimas 24h",
    painEyebrow: "Se você vive apagando incêndio…",
    painHeadline: "Talvez esteja remando <em>contra a maré cósmica</em>.",
    painBody: "Cada mês tem uma energia. Cada trânsito abre ou fecha portas. Quando você planeja sem esse mapa, gasta força onde não precisa e perde as janelas certas. <strong>Timing é tudo — e ele pode ser previsto.</strong>",
    pillarsEyebrow: "O que você vai receber",
    pillarsHeadline: "Seu ano decodificado mês a mês",
    pillars: [
      { icon: Clock, title: "Calendário Mês a Mês", desc: "Energia dominante de cada mês, com temas centrais e alertas." },
      { icon: TrendingUp, title: "Janelas de Oportunidade", desc: "Os melhores períodos pra lançamentos, mudanças e decisões grandes." },
      { icon: Heart, title: "Ciclos Amorosos", desc: "Meses de encontros, DR, união e reflexão nos seus vínculos." },
      { icon: Coins, title: "Ciclos Financeiros", desc: "Onde o dinheiro flui e onde é hora de conservar." },
      { icon: Moon, title: "Eclipses e Retrógrados", desc: "As datas críticas do ano e como se posicionar em cada uma." },
      { icon: Star, title: "Tema Anual", desc: "A lição-chave que os astros trazem pra você em 2026." },
    ],
    testimonialsEyebrow: "Depoimentos reais",
    testimonialsHeadline: "Previsões que se cumpriram",
    testimonials: [
      { name: "Marcelo T.", text: "Adiei o lançamento pra o mês indicado. Melhor decisão do ano — dobrou o resultado.", rating: 5 },
      { name: "Sofia R.", text: "Sabia dos 3 meses difíceis com antecedência. Passou muito mais leve quando chegou.", rating: 5 },
      { name: "Vanessa L.", text: "Uso como agenda cósmica. Consulto antes de qualquer decisão grande.", rating: 5 },
    ],
    guaranteeTitle: "Garantia de 7 dias",
    guaranteeBody: "Leia. Se não sentir que o mapa vale cada centavo, devolvemos <strong>100% do valor</strong>. Sem letras miúdas.",
    faqEyebrow: "Perguntas frequentes",
    faqHeadline: "Antes de mapear seu ano",
    faqs: [
      { q: "Cobre qual período?", a: "Os próximos 12 meses a partir da data da sua compra." },
      { q: "Preciso da hora exata do nascimento?", a: "Sim, é o ideal pra calcular trânsitos por casa astrológica. Se não souber, geramos com aproximação." },
      { q: "Em quanto tempo recebo?", a: "Poucos minutos após o pagamento. Chega no e-mail e WhatsApp." },
      { q: "É o mesmo que horóscopo anual da revista?", a: "Não. Aquele lê só o Sol. Aqui usamos seu mapa completo — Sol, Lua, Ascendente, planetas e casas." },
    ],
    finalEyebrow: "O calendário cósmico está esperando",
    finalHeadline: "Ou você improvisa o ano.\nOu você <em>joga com os astros</em>.",
    finalBody: "Menos que uma agenda executiva. Um mapa que vale por 12 meses de decisões mais certeiras.",
    dialogTitle: "Dados para sua previsão anual",
    dialogDesc: "A precisão de nascimento define a precisão dos trânsitos. Após o pagamento criamos sua conta e enviamos o PDF por e-mail.",
  },

  "sinastria-amorosa": {
    eyebrow: "Sinastria · Mapa do Casal",
    heroHeadline: "Vocês foram feitos um pro outro?",
    heroHeadlineAccent: "Os astros respondem.",
    heroSub: "A sinastria compara <strong>os dois mapas astrais e revela a química, os desafios e o potencial evolutivo</strong> da relação — namoro, casamento ou paixão nova.",
    heroBullets: [
      "Onde vocês se atraem magneticamente (e por quê)",
      "Os 3 principais focos de conflito — e como transformá-los",
      "A missão evolutiva que vocês têm juntos",
    ],
    socialProofLabel: "4.9 · +2.800 casais analisados",
    urgencyBar: "Mapa do casal — condição especial esta semana",
    livePurchase: "31 casais consultaram nas últimas 24h",
    painEyebrow: "Se a relação te confunde…",
    painHeadline: "Amor forte não basta se a <em>estrutura desalinha</em>.",
    painBody: "Vocês se amam mas brigam pelas mesmas coisas. Ou tudo flui, mas você duvida do futuro. Sinastria mostra <strong>onde a relação é feita pra durar e onde precisa de consciência ativa</strong>.",
    pillarsEyebrow: "O que a sinastria revela",
    pillarsHeadline: "6 camadas da relação de vocês",
    pillars: [
      { icon: Heart, title: "Química Vênus-Marte", desc: "A química afetiva e sexual entre os dois — atração real x construída." },
      { icon: HeartHandshake, title: "Compatibilidade emocional", desc: "Como suas Luas se relacionam e o que cada um precisa emocionalmente." },
      { icon: Handshake, title: "Aspectos harmônicos", desc: "Os pontos de encaixe natural — onde vocês se completam sem esforço." },
      { icon: Flame, title: "Aspectos tensos", desc: "Os conflitos previsíveis e como transformá-los em crescimento." },
      { icon: InfinityIcon, title: "Karma do casal", desc: "O vínculo de vidas passadas e a lição que vocês têm juntos." },
      { icon: Star, title: "Potencial evolutivo", desc: "O que essa relação constrói se for cultivada com consciência." },
    ],
    testimonialsEyebrow: "Depoimentos de casais",
    testimonialsHeadline: "Casais que se enxergaram",
    testimonials: [
      { name: "Léo & Carol", text: "Lemos juntos e chorávamos. Entendemos padrões de anos em uma tarde.", rating: 5 },
      { name: "Julia M.", text: "Descobri que o conflito repetido tinha nome — e uma saída concreta.", rating: 5 },
      { name: "Renata & Igor", text: "Decidimos casar depois dessa leitura. Vimos o quanto tem base pra isso.", rating: 5 },
    ],
    guaranteeTitle: "Garantia de 7 dias",
    guaranteeBody: "Leia com seu parceiro. Se não sentir que valeu, devolvemos <strong>100% do valor</strong>.",
    faqEyebrow: "Perguntas frequentes",
    faqHeadline: "Antes de comparar os mapas",
    faqs: [
      { q: "Preciso dos dados dos dois?", a: "Sim — nome, data, hora e local de nascimento de ambos." },
      { q: "Serve pra relação que ainda não começou?", a: "Sim. Muitas pessoas usam pra decidir avançar (ou não) com alguém." },
      { q: "E se meu parceiro não souber a hora?", a: "Geramos com aproximação. A leitura fica um pouco menos precisa nas casas, mas o essencial se mantém." },
      { q: "Em quanto tempo recebo?", a: "Poucos minutos após o pagamento. Chega no e-mail e WhatsApp." },
    ],
    finalEyebrow: "Os dois mapas esperam ser lidos juntos",
    finalHeadline: "Ou vocês seguem no achismo.\nOu <em>enxergam a relação</em>.",
    finalBody: "Menos que um jantar a dois. Uma leitura que redefine como vocês se relacionam.",
    dialogTitle: "Dados do casal",
    dialogDesc: "Preencha os dados dos dois. Após o pagamento criamos sua conta e enviamos o PDF por e-mail.",
  },

  "numerologia-cabalistica": {
    eyebrow: "Numerologia Cabalística · Análise Sagrada",
    heroHeadline: "Seu nome não é acaso.",
    heroHeadlineAccent: "É a chave da sua missão.",
    heroSub: "A <strong>numerologia cabalística</strong> traduz seu nome em números sagrados que revelam missão, dons, desafios e o caminho de realização da sua alma.",
    heroBullets: [
      "O número do seu Anjo Cabalístico e a proteção que ele oferece",
      "Sua Missão de Vida decifrada pela Árvore da Vida",
      "Os desafios kármicos ocultos no seu nome de batismo",
    ],
    socialProofLabel: "4.9 · +2.600 análises",
    urgencyBar: "Análise cabalística — condição especial ativa",
    livePurchase: "29 pessoas descobriram nas últimas 24h",
    painEyebrow: "Se você sente que veio pra algo…",
    painHeadline: "Seu nome já sussurra <em>qual é</em>.",
    painBody: "Cada letra do seu nome tem um valor. Cada número, uma frequência. Somados, revelam a arquitetura sagrada da sua vinda aqui. <strong>Ignorar isso é caminhar de olhos vendados.</strong>",
    pillarsEyebrow: "O que sua análise revela",
    pillarsHeadline: "6 números sagrados do seu nome",
    pillars: [
      { icon: Sparkle, title: "Anjo Cabalístico", desc: "Seu anjo regente, a proteção e o dom espiritual que ele traz." },
      { icon: Target, title: "Missão de Vida", desc: "O propósito central pelo qual sua alma veio nesta encarnação." },
      { icon: Gem, title: "Dons Inatos", desc: "Talentos naturais inscritos no seu nome que muitas vezes você ignora." },
      { icon: Flame, title: "Karmas do Nome", desc: "Padrões e provas que sua alma trouxe pra resolver aqui." },
      { icon: BookOpen, title: "Ano Pessoal", desc: "Qual é o tema numerológico do seu ano atual — e o que ele exige de você." },
      { icon: Compass, title: "Caminho de Realização", desc: "A direção específica onde seus números convergem em sucesso e paz." },
    ],
    testimonialsEyebrow: "Depoimentos",
    testimonialsHeadline: "Descobriram a assinatura da alma",
    testimonials: [
      { name: "Cristina B.", text: "Meu nome fez sentido pela primeira vez. Chorei ao ler a missão de vida.", rating: 5 },
      { name: "Paulo A.", text: "O anjo cabalístico me acompanha desde então. Nunca mais decidi sozinho.", rating: 5 },
      { name: "Denise F.", text: "Coisa séria. Me mostrou padrões kármicos que reconheci na hora.", rating: 5 },
    ],
    guaranteeTitle: "Garantia de 7 dias",
    guaranteeBody: "Se a análise não te trouxer reconhecimento profundo, devolvemos <strong>100% do valor</strong>.",
    faqEyebrow: "Perguntas frequentes",
    faqHeadline: "Antes de decifrar seu nome",
    faqs: [
      { q: "Qual nome eu uso?", a: "O nome completo de batismo, como está no registro. É esse que carrega a vibração original." },
      { q: "Em quanto tempo recebo?", a: "Poucos minutos após o pagamento. Chega no e-mail e WhatsApp." },
      { q: "Serve pra quem trocou de nome?", a: "Sim — analisamos o de batismo e o atual, mostrando o que cada um ativa." },
      { q: "Preciso saber cabala?", a: "Não. Tudo é explicado em linguagem clara, como um mentor te contando." },
    ],
    finalEyebrow: "Sua assinatura sagrada está aqui",
    finalHeadline: "Ou você segue no escuro.\nOu <em>decifra seu nome</em>.",
    finalBody: "Menos que um livro. Uma análise que vale por uma vida inteira de reconhecimento.",
    dialogTitle: "Dados para sua análise",
    dialogDesc: "Preencha com o nome completo de batismo. Após o pagamento criamos sua conta e enviamos o PDF por e-mail.",
  },

  "numerologia-do-casal": {
    eyebrow: "Numerologia do Casal · Análise Vibracional",
    heroHeadline: "O amor tem números.",
    heroHeadlineAccent: "E os seus contam uma história.",
    heroSub: "A <strong>numerologia do casal</strong> compara os números vibracionais dos dois nomes e datas — revelando compatibilidade, desafios e o propósito da união.",
    heroBullets: [
      "Compatibilidade numérica entre vocês (%)",
      "O número regente da relação e o que ele exige",
      "Os anos difíceis do casal e como atravessá-los",
    ],
    socialProofLabel: "4.9 · +2.100 casais",
    urgencyBar: "Análise do casal — condição especial esta semana",
    livePurchase: "26 casais consultaram nas últimas 24h",
    painEyebrow: "Se algo repete no casal…",
    painHeadline: "Talvez seja a <em>vibração numerológica</em>.",
    painBody: "Vocês tentam de tudo e a mesma briga volta. Não é falta de amor — é dissonância entre números que ninguém te ensinou a ler. <strong>Quando você entende os números, transforma a relação.</strong>",
    pillarsEyebrow: "O que a análise revela",
    pillarsHeadline: "6 números da união",
    pillars: [
      { icon: Heart, title: "Compatibilidade", desc: "O percentual real de harmonia entre os números principais dos dois." },
      { icon: Users, title: "Número do Casal", desc: "O número regente que rege a relação — e o que ele pede de vocês." },
      { icon: Sparkle, title: "Missão do Casal", desc: "Por que vocês se encontraram nesta vida — a lição-chave da união." },
      { icon: Clock, title: "Ano Pessoal Combinado", desc: "O tema do ano de vocês como casal e as decisões que ele favorece." },
      { icon: Flame, title: "Desafios Numéricos", desc: "Os atritos previsíveis por diferença vibracional — com saídas concretas." },
      { icon: Star, title: "Ciclos de Prosperidade", desc: "Os melhores momentos pra decisões grandes: morar junto, casar, empreender." },
    ],
    testimonialsEyebrow: "Depoimentos",
    testimonialsHeadline: "Casais que se leram nos números",
    testimonials: [
      { name: "Ana & Ricardo", text: "Nos vimos preto no branco. Entendemos por que o mesmo tema volta e como sair.", rating: 5 },
      { name: "Vitor & Bia", text: "A missão do casal fez sentido total. Nos aproximou de um jeito diferente.", rating: 5 },
      { name: "Sara T.", text: "Ler antes de casar salvou muita conversa difícil depois.", rating: 5 },
    ],
    guaranteeTitle: "Garantia de 7 dias",
    guaranteeBody: "Se não sentir que valeu, devolvemos <strong>100% do valor</strong>. Sem burocracia.",
    faqEyebrow: "Perguntas frequentes",
    faqHeadline: "Antes de somar os números",
    faqs: [
      { q: "Preciso dos dados dos dois?", a: "Sim — nomes completos de batismo e datas de nascimento de ambos." },
      { q: "Em quanto tempo recebo?", a: "Poucos minutos após o pagamento. Chega no e-mail e WhatsApp." },
      { q: "Serve pra relação nova?", a: "Sim, e é onde mais economiza tempo — você já entende o que essa união pede." },
      { q: "É a mesma coisa que sinastria astrológica?", a: "Complementar. Sinastria lê astros; numerologia lê nomes e datas. Juntas, cobrem tudo." },
    ],
    finalEyebrow: "Os números do casal esperam ser lidos",
    finalHeadline: "Ou vocês repetem o ciclo.\nOu <em>quebram o código</em>.",
    finalBody: "Menos que um jantar a dois. Uma leitura que reorganiza a relação.",
    dialogTitle: "Dados do casal",
    dialogDesc: "Preencha nomes completos de batismo e datas. Após o pagamento criamos sua conta e enviamos o PDF por e-mail.",
  },

  "mapa-vocacao-carreira": {
    eyebrow: "Vocação e Carreira · Chamado da Alma",
    heroHeadline: "Você não veio pra qualquer trabalho.",
    heroHeadlineAccent: "Veio pra um chamado.",
    heroSub: "Um mapa astrológico focado em <strong>propósito profissional, dons naturais e o momento certo pra virar de rota</strong> — pra quem sente que está no lugar errado.",
    heroBullets: [
      "Sua vocação real — o que Meio-do-Céu e Casa 10 dizem",
      "Talentos escondidos que o mercado pagaria pra ter",
      "As janelas dos próximos 12 meses pra mudar de carreira",
    ],
    socialProofLabel: "4.9 · +2.400 profissionais",
    urgencyBar: "Mapa da carreira — condição especial ativa",
    livePurchase: "38 pessoas descobriram nas últimas 24h",
    painEyebrow: "Se o trabalho te esvazia…",
    painHeadline: "Talvez você esteja no <em>papel errado</em>.",
    painBody: "Domingo à noite pesa. Você funciona, mas não brilha. Não é falta de esforço — é falta de alinhamento. <strong>Sua alma veio pra outra coisa e seu mapa mostra qual.</strong>",
    pillarsEyebrow: "O que você vai descobrir",
    pillarsHeadline: "6 pilares da sua vocação",
    pillars: [
      { icon: Briefcase, title: "Meio-do-Céu", desc: "O ponto do mapa que aponta o brilho profissional — sua vitrine natural." },
      { icon: Landmark, title: "Casa 10 e Casa 6", desc: "Como você quer ser reconhecido e como funciona na rotina de trabalho." },
      { icon: Gem, title: "Dons Latentes", desc: "Talentos naturais no seu mapa que ainda não viraram profissão." },
      { icon: Shield, title: "Saturno na Carreira", desc: "A prova que você precisa atravessar pra colher autoridade real." },
      { icon: TrendingUp, title: "Janelas de Virada", desc: "Os melhores meses dos próximos 12 pra decisões profissionais grandes." },
      { icon: Compass, title: "Rota Alinhada", desc: "As áreas específicas onde seu propósito, dom e mercado se encontram." },
    ],
    testimonialsEyebrow: "Depoimentos",
    testimonialsHeadline: "Encontraram o caminho certo",
    testimonials: [
      { name: "Rodrigo S.", text: "Larguei o cargo estável. Nunca ganhei tão bem — nem me senti tão vivo.", rating: 5 },
      { name: "Amanda L.", text: "O mapa apontou pra design. Fiz a transição e triplicou meu faturamento.", rating: 5 },
      { name: "Fabio M.", text: "Confirmou o que eu sentia. Tomei coragem pra o próximo passo.", rating: 5 },
    ],
    guaranteeTitle: "Garantia de 7 dias",
    guaranteeBody: "Se o mapa não te trouxer clareza real, devolvemos <strong>100% do valor</strong>. Sem risco.",
    faqEyebrow: "Perguntas frequentes",
    faqHeadline: "Antes de virar de rota",
    faqs: [
      { q: "Preciso da hora exata do nascimento?", a: "Sim — Meio-do-Céu e Casa 10 dependem dela. Se não souber, geramos com aproximação." },
      { q: "Serve pra quem já é empreendedor?", a: "Sim. Mostra onde alinhar melhor o negócio ao seu dom natural." },
      { q: "Em quanto tempo recebo?", a: "Poucos minutos após o pagamento. Chega no e-mail e WhatsApp." },
      { q: "É genérico como teste de perfil?", a: "Não. É personalizado pelo seu mapa único, com áreas e janelas específicas." },
    ],
    finalEyebrow: "O chamado está esperando resposta",
    finalHeadline: "Ou você fica no cargo errado.\nOu você <em>segue o mapa</em>.",
    finalBody: "Menos que um curso curto. Um mapa que pode redefinir a próxima década profissional.",
    dialogTitle: "Dados para seu mapa de carreira",
    dialogDesc: "A precisão do nascimento define a precisão da vocação. Após o pagamento criamos sua conta e enviamos o PDF por e-mail.",
  },

  "mapa-prosperidade-financeira": {
    eyebrow: "Prosperidade Financeira · Mapa da Abundância",
    heroHeadline: "O dinheiro tem uma rota.",
    heroHeadlineAccent: "A sua está escrita.",
    heroSub: "Um mapa astrológico focado em <strong>padrões financeiros, crenças de escassez herdadas e as janelas cósmicas pra prosperar</strong> no seu próximo ciclo.",
    heroBullets: [
      "Suas crenças invisíveis que travam a prosperidade",
      "Onde o dinheiro flui pra você (e onde ele escoa)",
      "Os meses de abertura financeira dos próximos 12",
    ],
    socialProofLabel: "4.9 · +2.900 mapas gerados",
    urgencyBar: "Mapa da prosperidade — oferta ativa esta semana",
    livePurchase: "41 pessoas mapearam nas últimas 24h",
    painEyebrow: "Se o dinheiro entra e some…",
    painHeadline: "Não é falta de esforço. É <em>padrão inconsciente</em>.",
    painBody: "Você trabalha, ganha, e nunca fica. Ou ganha bem e sabota. Isso não é aleatório — é um <strong>padrão financeiro herdado e inscrito no seu mapa</strong>, esperando ser rompido.",
    pillarsEyebrow: "O que você vai desvendar",
    pillarsHeadline: "6 chaves da sua prosperidade",
    pillars: [
      { icon: Coins, title: "Casa 2 — Recursos", desc: "Sua relação natural com dinheiro, valor pessoal e o que você sabe monetizar." },
      { icon: Building2, title: "Casa 8 — Bens Compartilhados", desc: "Investimentos, sociedades, heranças e recursos que passam pelas suas mãos." },
      { icon: Gem, title: "Vênus Financeira", desc: "O que atrai dinheiro pra você — muito além do óbvio." },
      { icon: Scale, title: "Júpiter e Saturno", desc: "Expansão x limite — como você equilibra abundância e responsabilidade." },
      { icon: Flame, title: "Crenças Herdadas", desc: "Padrões financeiros da linhagem que você carrega sem perceber." },
      { icon: TrendingUp, title: "Ciclos de Prosperidade", desc: "As janelas específicas do seu ano pra investir, empreender ou negociar." },
    ],
    testimonialsEyebrow: "Depoimentos",
    testimonialsHeadline: "Virada financeira real",
    testimonials: [
      { name: "Camila P.", text: "Reconheci uma crença da minha mãe que era minha também. Rompi e o dinheiro passou a ficar.", rating: 5 },
      { name: "Bruno F.", text: "Investi no mês certo. Triplicou. Levo o mapa a sério desde então.", rating: 5 },
      { name: "Larissa M.", text: "Entendi por que sabotava contratos grandes. Assinei o próximo sem drama.", rating: 5 },
    ],
    guaranteeTitle: "Garantia de 7 dias",
    guaranteeBody: "Se o mapa não te trouxer clareza financeira real, devolvemos <strong>100% do valor</strong>.",
    faqEyebrow: "Perguntas frequentes",
    faqHeadline: "Antes de destravar a rota",
    faqs: [
      { q: "É promessa de enriquecimento?", a: "Não. É um mapa que mostra padrões, dons e janelas. A ação continua sendo sua." },
      { q: "Preciso da hora de nascimento?", a: "Sim, é o ideal pra ler Casas 2 e 8. Se não souber, geramos com aproximação." },
      { q: "Serve pra quem tem dívida?", a: "Sim — e é onde mais ajuda. Você entende o padrão que gerou a dívida antes de repetir." },
      { q: "Em quanto tempo recebo?", a: "Poucos minutos após o pagamento. Chega no e-mail e WhatsApp." },
    ],
    finalEyebrow: "A rota da abundância está no seu mapa",
    finalHeadline: "Ou você segue no ciclo.\nOu <em>rompe o padrão</em>.",
    finalBody: "Menos que uma consulta financeira. Um mapa que muda sua relação com dinheiro pra sempre.",
    dialogTitle: "Dados para seu mapa financeiro",
    dialogDesc: "A precisão do nascimento aprofunda a leitura. Após o pagamento criamos sua conta e enviamos o PDF por e-mail.",
  },

  "mapa-familiar-ancestral": {
    eyebrow: "Família e Ancestralidade · Cura da Linhagem",
    heroHeadline: "Você carrega uma linhagem.",
    heroHeadlineAccent: "E ela também espera cura.",
    heroSub: "Um mapa que revela <strong>padrões familiares herdados, feridas da linhagem e a missão de cura</strong> que sua alma trouxe pra a sua árvore ancestral.",
    heroBullets: [
      "O padrão emocional herdado da sua mãe (Casa 4)",
      "A ferida ancestral que se repete há gerações",
      "Seu papel na cura da linhagem — o que você veio quebrar",
    ],
    socialProofLabel: "4.9 · +1.800 leituras",
    urgencyBar: "Cura da linhagem — condição especial ativa",
    livePurchase: "22 pessoas mapearam nas últimas 24h",
    painEyebrow: "Se um padrão se repete há gerações…",
    painHeadline: "Talvez ele não seja <em>seu</em>.",
    painBody: "As mesmas dores da sua mãe. Os mesmos silêncios do seu pai. Você promete que não vai repetir — e repete. É porque isso vem antes de você. <strong>E só se rompe com consciência ativa.</strong>",
    pillarsEyebrow: "O que o mapa revela",
    pillarsHeadline: "6 camadas da sua linhagem",
    pillars: [
      { icon: Waves, title: "Casa 4 — Raízes", desc: "A herança emocional materna e o que você carrega da linhagem feminina." },
      { icon: Landmark, title: "Casa 10 — Autoridade", desc: "A figura paterna e o padrão de autoridade herdado da linhagem masculina." },
      { icon: Moon, title: "Lua — Ferida Emocional", desc: "A ferida herdada que se repete até ser reconhecida e transformada." },
      { icon: InfinityIcon, title: "Karma Ancestral", desc: "Padrões da linhagem que sua alma escolheu resolver nesta vida." },
      { icon: Sprout, title: "Missão de Cura", desc: "O que você veio quebrar pra que os próximos não repitam." },
      { icon: Feather, title: "Ritual de Libertação", desc: "Práticas específicas pra honrar e liberar cada padrão herdado." },
    ],
    testimonialsEyebrow: "Depoimentos",
    testimonialsHeadline: "Curaram a árvore",
    testimonials: [
      { name: "Isabel R.", text: "Chorei entendendo minha mãe. E chorei entendendo o quanto isso não precisava ser meu.", rating: 5 },
      { name: "Thiago M.", text: "Descobri que carrego um padrão do meu avô. Rompi um contrato tóxico depois.", rating: 5 },
      { name: "Vera P.", text: "Uso os rituais até hoje. Sinto a linhagem mais leve — em mim e nos meus filhos.", rating: 5 },
    ],
    guaranteeTitle: "Garantia de 7 dias",
    guaranteeBody: "Se a leitura não tocar um reconhecimento profundo, devolvemos <strong>100% do valor</strong>.",
    faqEyebrow: "Perguntas frequentes",
    faqHeadline: "Antes de olhar pra linhagem",
    faqs: [
      { q: "Preciso saber a história dos meus avós?", a: "Não. O mapa lê os padrões pelos astros. Você reconhece na hora." },
      { q: "É pesado emocionalmente?", a: "Toca fundo, mas é organizador. Não abrimos ferida sem oferecer o ritual de cura." },
      { q: "Preciso da hora de nascimento?", a: "Sim, é o ideal pra ler Casa 4 e Casa 10. Se não souber, geramos com aproximação." },
      { q: "Em quanto tempo recebo?", a: "Poucos minutos após o pagamento. Chega no e-mail e WhatsApp." },
    ],
    finalEyebrow: "Sua linhagem está esperando por você",
    finalHeadline: "Ou o padrão passa adiante.\nOu você <em>cura a árvore</em>.",
    finalBody: "Menos que uma sessão de terapia. Um mapa que pode encerrar séculos de repetição.",
    dialogTitle: "Dados para seu mapa ancestral",
    dialogDesc: "A precisão do nascimento aprofunda a leitura. Após o pagamento criamos sua conta e enviamos o PDF por e-mail.",
  },

  "mapa-saude-integrativa": {
    eyebrow: "Saúde Integrativa · Corpo e Alma",
    heroHeadline: "Seu corpo fala.",
    heroHeadlineAccent: "Os astros traduzem.",
    heroSub: "Um mapa astrológico focado em <strong>tendências de vitalidade, pontos sensíveis do corpo e práticas integrativas</strong> alinhadas com sua constituição energética.",
    heroBullets: [
      "Suas fragilidades naturais — o que preservar preventivamente",
      "Sua zona de vitalidade — onde investir energia gera saúde",
      "Práticas integrativas ideais pro seu mapa (não genéricas)",
    ],
    socialProofLabel: "4.9 · +1.700 mapas gerados",
    urgencyBar: "Mapa da saúde — condição especial ativa",
    livePurchase: "24 pessoas mapearam nas últimas 24h",
    painEyebrow: "Se o corpo pede pausa…",
    painHeadline: "Talvez ele esteja falando <em>há tempos</em>.",
    painBody: "Você acumula tensão sem perceber. Testa dietas, meditação, academia — e nada dura. Não é falta de disciplina — é falta do mapa que mostra o que <strong>o SEU corpo específico precisa</strong>.",
    pillarsEyebrow: "O que o mapa revela",
    pillarsHeadline: "6 camadas da sua vitalidade",
    pillars: [
      { icon: Activity, title: "Casa 6 — Rotina do Corpo", desc: "Como sua saúde responde à rotina — o que sustenta e o que desgasta." },
      { icon: Sun, title: "Sol e Ascendente", desc: "Sua vitalidade base e a constituição energética natural." },
      { icon: Moon, title: "Lua e Emoções", desc: "Como emoções não digeridas viram sintomas no seu corpo." },
      { icon: Leaf, title: "Práticas Alinhadas", desc: "Yoga, medicinas integrativas, alimentação: o que combina com seu mapa." },
      { icon: Shield, title: "Pontos Sensíveis", desc: "Áreas do corpo com tendência natural — pra prevenção, não pra susto." },
      { icon: Sparkle, title: "Janelas de Cura", desc: "Os melhores meses pra iniciar processos de saúde, jejum ou cirurgia eletiva." },
    ],
    testimonialsEyebrow: "Depoimentos",
    testimonialsHeadline: "Reconciliaram com o corpo",
    testimonials: [
      { name: "Mariana T.", text: "Descobri que meu tipo pede ritmo, não intensidade. Mudei tudo — e o corpo agradece.", rating: 5 },
      { name: "Paulo R.", text: "Comecei acupuntura no mês indicado. Diferença brutal.", rating: 5 },
      { name: "Fernanda L.", text: "Parei de brigar com meu corpo. Aceitei o ritmo dele e ganhei energia.", rating: 5 },
    ],
    guaranteeTitle: "Garantia de 7 dias",
    guaranteeBody: "Se não sentir que o mapa mudou como você cuida de si, devolvemos <strong>100% do valor</strong>.",
    faqEyebrow: "Perguntas frequentes",
    faqHeadline: "Antes de escutar seu corpo",
    faqs: [
      { q: "Substitui médico?", a: "Não. É complementar. Mostra tendências e alinhamentos — nunca diagnóstico ou tratamento clínico." },
      { q: "Preciso da hora de nascimento?", a: "Sim, é o ideal pra ler Casa 6 e Ascendente. Se não souber, geramos com aproximação." },
      { q: "Serve pra atleta?", a: "Muito bem. Mostra como periodizar treino e recuperação de acordo com seu tipo." },
      { q: "Em quanto tempo recebo?", a: "Poucos minutos após o pagamento. Chega no e-mail e WhatsApp." },
    ],
    finalEyebrow: "Seu corpo já sabe. Falta você ouvir",
    finalHeadline: "Ou você força o corpo.\nOu você <em>escuta o mapa</em>.",
    finalBody: "Menos que uma consulta particular. Um mapa que muda como você cuida de si — pra sempre.",
    dialogTitle: "Dados para seu mapa de saúde",
    dialogDesc: "A precisão do nascimento aprofunda a leitura. Após o pagamento criamos sua conta e enviamos o PDF por e-mail.",
  },

  "mapa-das-amizades": {
    eyebrow: "Amizades e Círculo Social · Análise",
    heroHeadline: "Diga-me com quem andas.",
    heroHeadlineAccent: "Seu mapa dirá quem és.",
    heroSub: "Um mapa astrológico focado em <strong>padrões sociais, perfil de amigos que combinam com você e feridas de pertencimento</strong> que moldam seu círculo.",
    heroBullets: [
      "O tipo de pessoa que verdadeiramente te nutre",
      "As amizades tóxicas que você atrai (e por quê)",
      "Sua ferida de pertencimento — e como curar",
    ],
    socialProofLabel: "4.9 · +1.500 análises",
    urgencyBar: "Mapa das amizades — condição especial esta semana",
    livePurchase: "19 pessoas mapearam nas últimas 24h",
    painEyebrow: "Se você se sente sozinha em grupo…",
    painHeadline: "Talvez você esteja no <em>círculo errado</em>.",
    painBody: "Rodeada de gente mas sem ninguém real. Ou com amizades antigas que já não encaixam. Não é seletividade — é <strong>desalinhamento entre seu mapa e o círculo que você mantém</strong>.",
    pillarsEyebrow: "O que o mapa revela",
    pillarsHeadline: "6 chaves do seu círculo",
    pillars: [
      { icon: Users, title: "Casa 11 — Amigos e Grupos", desc: "O tipo de tribo que te nutre e onde você se sente pertencer." },
      { icon: Heart, title: "Vênus Social", desc: "Como você constrói afeto fora do amor romântico — na amizade." },
      { icon: Sparkle, title: "Perfil Ideal", desc: "As qualidades específicas em outra pessoa que te fazem florescer." },
      { icon: Flame, title: "Amizades Sabotadoras", desc: "O tipo que você repete atraindo — e a ferida que sustenta o padrão." },
      { icon: HeartHandshake, title: "Você como Amiga", desc: "Como você aparece pros seus — dons e sombras da sua presença." },
      { icon: Sprout, title: "Novo Círculo", desc: "Como abrir espaço pra amizades novas alinhadas com sua fase atual." },
    ],
    testimonialsEyebrow: "Depoimentos",
    testimonialsHeadline: "Refizeram o círculo",
    testimonials: [
      { name: "Beatriz S.", text: "Entendi por que eu me esvaziava com certas pessoas. Redesenhei minhas amizades.", rating: 5 },
      { name: "Camila V.", text: "O perfil ideal bateu com quem eu já sentia — e ainda não priorizava.", rating: 5 },
      { name: "Renato F.", text: "Descobri como apareço pros amigos. Ajustei coisas e as relações ficaram mais leves.", rating: 5 },
    ],
    guaranteeTitle: "Garantia de 7 dias",
    guaranteeBody: "Se a leitura não te trouxer clareza sobre seus vínculos, devolvemos <strong>100% do valor</strong>.",
    faqEyebrow: "Perguntas frequentes",
    faqHeadline: "Antes de mapear seu círculo",
    faqs: [
      { q: "Serve pra quem tem poucos amigos?", a: "Sim — e ajuda muito. Mostra o padrão que restringe e o caminho pra abrir vínculos novos." },
      { q: "Preciso da hora de nascimento?", a: "Sim, é o ideal pra ler Casa 11. Se não souber, geramos com aproximação." },
      { q: "Serve pra ambiente de trabalho?", a: "Sim, aplica pra qualquer círculo social — clube, igreja, colegas, comunidade." },
      { q: "Em quanto tempo recebo?", a: "Poucos minutos após o pagamento. Chega no e-mail e WhatsApp." },
    ],
    finalEyebrow: "Seu círculo pode ser refeito",
    finalHeadline: "Ou você mantém o padrão.\nOu <em>escolhe sua tribo</em>.",
    finalBody: "Menos que uma noite fora. Uma leitura que muda quem caminha ao seu lado.",
    dialogTitle: "Dados para sua análise social",
    dialogDesc: "A precisão do nascimento aprofunda a leitura. Após o pagamento criamos sua conta e enviamos o PDF por e-mail.",
  },

  "mapa-da-personalidade": {
    eyebrow: "Personalidade Numerológica · Retrato da Alma",
    heroHeadline: "Você já é quem precisa ser.",
    heroHeadlineAccent: "Basta se enxergar.",
    heroSub: "Um retrato numerológico completo da <strong>sua personalidade, dons, sombras e o papel único</strong> que você veio interpretar nesta vida.",
    heroBullets: [
      "Seu Número de Expressão — como o mundo te percebe",
      "Seu Número de Alma — o que te move por dentro",
      "Seus talentos escondidos e sua sombra recorrente",
    ],
    socialProofLabel: "4.9 · +2.200 retratos",
    urgencyBar: "Retrato da alma — condição especial ativa",
    livePurchase: "27 pessoas descobriram nas últimas 24h",
    painEyebrow: "Se você ainda tenta se explicar…",
    painHeadline: "Talvez você só precise <em>se ler</em>.",
    painBody: "Você se sente muitas coisas ao mesmo tempo. Testes de personalidade te encaixam num quadrado. Sua alma não cabe em quadrado — cabe em números. <strong>Ler os seus é ver-se inteiro.</strong>",
    pillarsEyebrow: "O que o retrato revela",
    pillarsHeadline: "6 números da sua identidade",
    pillars: [
      { icon: Sun, title: "Número de Expressão", desc: "Como você aparece pro mundo — o papel que assume naturalmente." },
      { icon: Heart, title: "Número de Alma", desc: "O que realmente te move por dentro — seu impulso essencial." },
      { icon: Eye, title: "Número de Personalidade", desc: "A máscara que você mostra antes de se revelar." },
      { icon: Gem, title: "Dons Naturais", desc: "Talentos inscritos nos números que você pode desenvolver." },
      { icon: Flame, title: "Sombra Recorrente", desc: "O padrão que se repete quando você não está no seu melhor." },
      { icon: Compass, title: "Papel de Vida", desc: "A missão social que sua combinação numérica sustenta melhor." },
    ],
    testimonialsEyebrow: "Depoimentos",
    testimonialsHeadline: "Se reconheceram nos números",
    testimonials: [
      { name: "Aline R.", text: "Ler foi como me apresentar a mim mesma. Tudo fez sentido de um jeito novo.", rating: 5 },
      { name: "Diogo M.", text: "Entendi minha sombra sem me culpar. Isso foi libertador.", rating: 5 },
      { name: "Sabrina P.", text: "Guardo o PDF. Releio em momentos de dúvida — sempre me ancora.", rating: 5 },
    ],
    guaranteeTitle: "Garantia de 7 dias",
    guaranteeBody: "Se não sentir que se reconheceu profundamente, devolvemos <strong>100% do valor</strong>.",
    faqEyebrow: "Perguntas frequentes",
    faqHeadline: "Antes de ler-se",
    faqs: [
      { q: "Qual nome eu uso?", a: "O nome completo de batismo. É esse que carrega a vibração original da personalidade." },
      { q: "Em quanto tempo recebo?", a: "Poucos minutos após o pagamento. Chega no e-mail e WhatsApp." },
      { q: "É diferente de teste de perfil?", a: "Sim. Não te coloca em categoria — mostra sua combinação numérica única, sem gaveta." },
      { q: "Serve pra desenvolvimento pessoal?", a: "Ideal. Muitas pessoas usam como base pra terapia, coaching ou decisões de carreira." },
    ],
    finalEyebrow: "O retrato está pronto pra ser revelado",
    finalHeadline: "Ou você se cobra por não caber.\nOu você <em>se lê inteiro</em>.",
    finalBody: "Menos que um livro. Um retrato que te acompanha pela vida toda.",
    dialogTitle: "Dados para seu retrato numerológico",
    dialogDesc: "Preencha com o nome completo de batismo. Após o pagamento criamos sua conta e enviamos o PDF por e-mail.",
  },

  "cabala-pessoal": {
    eyebrow: "Cabala Pessoal · Árvore da Vida",
    heroHeadline: "Existe uma árvore sagrada.",
    heroHeadlineAccent: "E ela tem o seu nome.",
    heroSub: "Uma leitura da <strong>Árvore da Vida cabalística aplicada à sua alma</strong> — mostrando os Sephirot que te regem, o caminho iniciático e sua conexão com o divino.",
    heroBullets: [
      "Os Sephirot dominantes no seu mapa cabalístico",
      "Seu caminho iniciático na Árvore da Vida",
      "As letras hebraicas sagradas ligadas à sua alma",
    ],
    socialProofLabel: "4.9 · +1.400 leituras",
    urgencyBar: "Leitura cabalística — condição especial ativa",
    livePurchase: "18 pessoas leram nas últimas 24h",
    painEyebrow: "Se você busca algo mais profundo…",
    painHeadline: "A Árvore da Vida <em>já te contém</em>.",
    painBody: "Você já ouviu sobre karma, sobre alma, sobre missão. Mas falta a estrutura sagrada que organiza tudo. <strong>A Cabala é o mapa mais antigo da alma humana — e ele tem o seu nome escrito.</strong>",
    pillarsEyebrow: "O que a leitura revela",
    pillarsHeadline: "6 chaves da sua cabala pessoal",
    pillars: [
      { icon: Sparkle, title: "Sephirot Dominantes", desc: "As esferas sagradas mais ativas na sua alma e o que cada uma pede de você." },
      { icon: BookOpen, title: "Letras Hebraicas", desc: "As letras sagradas ligadas ao seu nome e as vibrações que elas ativam." },
      { icon: Compass, title: "Caminho Iniciático", desc: "A rota da sua evolução dentro da Árvore da Vida." },
      { icon: Shield, title: "Anjo Regente", desc: "O anjo cabalístico da sua data — proteção, dom e missão que ele entrega." },
      { icon: KeyRound, title: "Portais Kármicos", desc: "As Sephirot que trazem lição forte pra sua alma nesta encarnação." },
      { icon: Gem, title: "Prática Diária", desc: "Meditações e mantras cabalísticos ideais pro seu mapa." },
    ],
    testimonialsEyebrow: "Depoimentos",
    testimonialsHeadline: "Entraram na Árvore",
    testimonials: [
      { name: "Miriam L.", text: "Nunca tinha estudado Cabala. Saí querendo mergulhar de cabeça — tudo fez sentido.", rating: 5 },
      { name: "Eduardo S.", text: "O anjo regente virou parte da minha rotina. Sinto amparo real.", rating: 5 },
      { name: "Clara F.", text: "As letras hebraicas ligadas ao meu nome me tocaram como se sempre soubesse.", rating: 5 },
    ],
    guaranteeTitle: "Garantia de 7 dias",
    guaranteeBody: "Se a leitura não te tocar profundamente, devolvemos <strong>100% do valor</strong>.",
    faqEyebrow: "Perguntas frequentes",
    faqHeadline: "Antes de entrar na Árvore",
    faqs: [
      { q: "Preciso ser judeu ou religioso?", a: "Não. A Cabala é uma tradição mística universal — aberta a qualquer buscador sincero." },
      { q: "Em quanto tempo recebo?", a: "Poucos minutos após o pagamento. Chega no e-mail e WhatsApp." },
      { q: "É muito técnica?", a: "Não. Traduzimos toda a simbologia com clareza — como um mestre te apresentando." },
      { q: "Serve pra prática espiritual?", a: "Ideal. Você sai com meditações e mantras específicos pro seu caminho." },
    ],
    finalEyebrow: "A Árvore te chama há tempos",
    finalHeadline: "Ou você adia a iniciação.\nOu <em>entra na Árvore</em>.",
    finalBody: "Menos que um curso introdutório. Uma leitura que abre um portal místico pra vida toda.",
    dialogTitle: "Dados para sua cabala pessoal",
    dialogDesc: "Preencha com o nome completo de batismo. Após o pagamento criamos sua conta e enviamos o PDF por e-mail.",
  },

  "meditacao-cabalistica-personalizada": {
    eyebrow: "Meditação Cabalística · Guiada pela Sua Alma",
    heroHeadline: "Uma meditação genérica",
    heroHeadlineAccent: "nunca vai tocar sua alma.",
    heroSub: "Uma meditação cabalística <strong>personalizada pelo seu nome e data</strong> — com visualização dos Sephirot, letras hebraicas e mantras alinhados à sua vibração.",
    heroBullets: [
      "Meditação guiada calibrada pela SUA cabala pessoal",
      "Mantras em hebraico com pronúncia e significado",
      "Sephirot ativados na visualização — não genéricos",
    ],
    socialProofLabel: "4.9 · +1.200 meditações",
    urgencyBar: "Meditação personalizada — oferta ativa esta semana",
    livePurchase: "16 pessoas iniciaram nas últimas 24h",
    painEyebrow: "Se apps de meditação não bastam…",
    painHeadline: "É porque eles falam com <em>todo mundo</em>.",
    painBody: "Você tenta meditar, mas a mente escapa. Testa apps, vídeos, mantras aleatórios. Falta <strong>uma meditação que fale a linguagem específica da sua alma</strong> — e isso a Cabala consegue calibrar.",
    pillarsEyebrow: "O que você recebe",
    pillarsHeadline: "6 elementos da sua meditação",
    pillars: [
      { icon: Sparkle, title: "Sephirot Pessoais", desc: "As esferas sagradas ativadas na visualização de acordo com o seu mapa." },
      { icon: BookOpen, title: "Letras Hebraicas", desc: "As letras ligadas ao seu nome, com pronúncia e visualização orientadas." },
      { icon: Feather, title: "Mantra Personalizado", desc: "Um mantra em hebraico calibrado pela sua vibração numerológica." },
      { icon: Waves, title: "Guia Sensorial", desc: "Roteiro completo — respiração, cor, imagem e som pra cada trecho." },
      { icon: Shield, title: "Anjo Regente", desc: "Invocação do seu anjo cabalístico no ápice da meditação." },
      { icon: Clock, title: "Prática Diária", desc: "Versão curta (7 min) e longa (25 min) pra encaixar na rotina." },
    ],
    testimonialsEyebrow: "Depoimentos",
    testimonialsHeadline: "Sentiram diferença já no primeiro uso",
    testimonials: [
      { name: "Luana T.", text: "Nunca tinha meditado de verdade. Com essa, eu senti — não só executei.", rating: 5 },
      { name: "Otavio M.", text: "O mantra virou parte do meu dia. Sinto ancoragem real.", rating: 5 },
      { name: "Renata C.", text: "Cabalística de verdade — e simples de seguir. Uso toda manhã.", rating: 5 },
    ],
    guaranteeTitle: "Garantia de 7 dias",
    guaranteeBody: "Se a meditação não te tocar profundamente, devolvemos <strong>100% do valor</strong>.",
    faqEyebrow: "Perguntas frequentes",
    faqHeadline: "Antes de sentar-se",
    faqs: [
      { q: "Preciso saber meditar?", a: "Não. A guia é passo a passo — respiração, imagem e som orientados." },
      { q: "Recebo áudio?", a: "Recebe o roteiro completo em PDF com pronúncia dos mantras. Áudio guiado é upgrade opcional." },
      { q: "Preciso ser religioso?", a: "Não. Cabala é uma tecnologia mística universal — aberta a qualquer prática." },
      { q: "Em quanto tempo recebo?", a: "Poucos minutos após o pagamento. Chega no e-mail e WhatsApp." },
    ],
    finalEyebrow: "Sua meditação está esperando",
    finalHeadline: "Ou você tenta com apps genéricos.\nOu <em>senta com sua alma</em>.",
    finalBody: "Menos que uma aula de yoga. Uma prática que te acompanha pela vida.",
    dialogTitle: "Dados para sua meditação personalizada",
    dialogDesc: "Preencha com o nome completo de batismo. Após o pagamento criamos sua conta e enviamos o PDF por e-mail.",
  },

  "mapa-empresarial": {
    eyebrow: "Mapa Empresarial · Bússola do Negócio",
    heroHeadline: "Toda empresa tem um mapa astral.",
    heroHeadlineAccent: "E o seu ainda não foi lido.",
    heroSub: "Um mapa astrológico do seu <strong>negócio (fundação, sócios, ciclos) e os melhores momentos pra lançar, contratar, girar</strong> — com precisão de tempo que planilha nenhuma dá.",
    heroBullets: [
      "O DNA astrológico da empresa (data de fundação)",
      "Ciclos de expansão e retração dos próximos 12 meses",
      "Melhores momentos pra lançamentos, contratações e sociedades",
    ],
    socialProofLabel: "4.9 · +900 negócios mapeados",
    urgencyBar: "Mapa empresarial — condição especial ativa",
    livePurchase: "14 empresas mapearam nas últimas 24h",
    painEyebrow: "Se o negócio vai bem, mas trava…",
    painHeadline: "Talvez o timing esteja <em>fora do ritmo cósmico</em>.",
    painBody: "Você lança e não decola. Contrata e desencaixa. Não é só execução — é <strong>alinhamento com os ciclos astrológicos do próprio negócio</strong>, que ninguém te ensinou a ler.",
    pillarsEyebrow: "O que o mapa revela",
    pillarsHeadline: "6 pilares do seu negócio",
    pillars: [
      { icon: Building2, title: "Mapa de Fundação", desc: "Análise completa do dia em que a empresa foi criada — seu DNA astral." },
      { icon: Handshake, title: "Sinastria com Sócios", desc: "Compatibilidade entre você, os sócios e o mapa do negócio." },
      { icon: TrendingUp, title: "Ciclos de Expansão", desc: "Meses cósmicos ideais pra crescer, investir e escalar." },
      { icon: Coins, title: "Ciclos Financeiros", desc: "Quando o dinheiro flui e quando é hora de conservar caixa." },
      { icon: Shield, title: "Zonas de Risco", desc: "Períodos de fragilidade — pra decisões defensivas em vez de ofensivas." },
      { icon: Clock, title: "Datas Estratégicas", desc: "Janelas específicas pra lançamentos, contratações e negociações grandes." },
    ],
    testimonialsEyebrow: "Depoimentos",
    testimonialsHeadline: "Empresários que apostaram no mapa",
    testimonials: [
      { name: "Marcelo A.", text: "Adiei o lançamento pra o mês indicado. Faturamento 2,4x maior do que projetávamos.", rating: 5 },
      { name: "Sofia P.", text: "Segurei uma contratação por 30 dias. Contratei a pessoa certa no mês certo.", rating: 5 },
      { name: "Rafael G.", text: "Uso como calendário estratégico. Não decido nada grande sem consultar.", rating: 5 },
    ],
    guaranteeTitle: "Garantia de 7 dias",
    guaranteeBody: "Se o mapa não te trouxer clareza estratégica real, devolvemos <strong>100% do investimento</strong>.",
    faqEyebrow: "Perguntas frequentes",
    faqHeadline: "Antes de mapear o negócio",
    faqs: [
      { q: "Preciso da hora de fundação da empresa?", a: "É o ideal. Se souber só a data, geramos com aproximação — ainda extremamente útil." },
      { q: "Serve pra empresa recém-criada?", a: "Sim, e é o momento mais importante — você já começa alinhado aos ciclos." },
      { q: "Cobre quantos meses?", a: "12 meses cheios a partir da data da compra, com destaque pros trimestres." },
      { q: "Em quanto tempo recebo?", a: "Poucos minutos após o pagamento. Chega no e-mail e WhatsApp." },
    ],
    finalEyebrow: "Seu negócio pede um plano cósmico",
    finalHeadline: "Ou você improvisa o ano.\nOu <em>joga com o mapa</em>.",
    finalBody: "Menos que um dia de consultoria. Um mapa estratégico que vale por 12 meses de decisões mais certeiras.",
    dialogTitle: "Dados da empresa",
    dialogDesc: "Preencha razão social, data, hora e local de fundação. Após o pagamento criamos sua conta e enviamos o PDF por e-mail.",
  },

};

export const PILL_ICONS = { Sparkles };
export function hasPersuasiveCopy(slug: string): boolean {
  return slug in PERSUASIVE_COPY;
}

