/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfissionaisRouteImport } from './routes/profissionais'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AtivacaoRouteImport } from './routes/ativacao'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as AuthenticatedTarotRouteImport } from './routes/_authenticated.tarot'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated.relatorios'
import { Route as AuthenticatedPdfCssRouteImport } from './routes/_authenticated.pdf-css'
import { Route as AuthenticatedOraculoRouteImport } from './routes/_authenticated.oraculo'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as AuthenticatedNumerologiaCabalisticaRouteImport } from './routes/_authenticated.numerologia-cabalistica'
import { Route as AuthenticatedNumerologiaRouteImport } from './routes/_authenticated.numerologia'
import { Route as AuthenticatedMeditacaoRouteImport } from './routes/_authenticated.meditacao'
import { Route as AuthenticatedMapaEmpresarialRouteImport } from './routes/_authenticated.mapa-empresarial'
import { Route as AuthenticatedMapaAstralRouteImport } from './routes/_authenticated.mapa-astral'
import { Route as AuthenticatedHoroscopoRouteImport } from './routes/_authenticated.horoscopo'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated.configuracoes'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated.clientes'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAddonsRouteImport } from './routes/_authenticated.addons'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated.admin.logs'
import { Route as ApiPublicManifestWebmanifestRouteImport } from './routes/api/public/manifest.webmanifest'
import { Route as ApiPublicManifestIconRouteImport } from './routes/api/public/manifest.icon'
import { Route as ApiPublicHooksMercadopagoRouteImport } from './routes/api/public/hooks/mercadopago'
import { Route as ApiPublicHooksDispatchOrdersRouteImport } from './routes/api/public/hooks/dispatch-orders'
import { Route as ApiPublicHooksDailyHoroscopeRouteImport } from './routes/api/public/hooks/daily-horoscope'
import { Route as ApiPublicHooksCrmFollowupsRouteImport } from './routes/api/public/hooks/crm-followups'
import { Route as AuthenticatedPSlugCheckoutRouteImport } from './routes/_authenticated.p.$slug.checkout'

const ProfissionaisRoute = ProfissionaisRouteImport.update({
  id: '/profissionais',
  path: '/profissionais',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivacaoRoute = AtivacaoRouteImport.update({
  id: '/ativacao',
  path: '/ativacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTarotRoute = AuthenticatedTarotRouteImport.update({
  id: '/tarot',
  path: '/tarot',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPdfCssRoute = AuthenticatedPdfCssRouteImport.update({
  id: '/pdf-css',
  path: '/pdf-css',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOraculoRoute = AuthenticatedOraculoRouteImport.update({
  id: '/oraculo',
  path: '/oraculo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNumerologiaCabalisticaRoute =
  AuthenticatedNumerologiaCabalisticaRouteImport.update({
    id: '/numerologia-cabalistica',
    path: '/numerologia-cabalistica',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNumerologiaRoute =
  AuthenticatedNumerologiaRouteImport.update({
    id: '/numerologia',
    path: '/numerologia',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeditacaoRoute = AuthenticatedMeditacaoRouteImport.update({
  id: '/meditacao',
  path: '/meditacao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapaEmpresarialRoute =
  AuthenticatedMapaEmpresarialRouteImport.update({
    id: '/mapa-empresarial',
    path: '/mapa-empresarial',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMapaAstralRoute = AuthenticatedMapaAstralRouteImport.update({
  id: '/mapa-astral',
  path: '/mapa-astral',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHoroscopoRoute = AuthenticatedHoroscopoRouteImport.update({
  id: '/horoscopo',
  path: '/horoscopo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAddonsRoute = AuthenticatedAddonsRouteImport.update({
  id: '/addons',
  path: '/addons',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicManifestWebmanifestRoute =
  ApiPublicManifestWebmanifestRouteImport.update({
    id: '/api/public/manifest/webmanifest',
    path: '/api/public/manifest/webmanifest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicManifestIconRoute = ApiPublicManifestIconRouteImport.update({
  id: '/api/public/manifest/icon',
  path: '/api/public/manifest/icon',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksMercadopagoRoute =
  ApiPublicHooksMercadopagoRouteImport.update({
    id: '/api/public/hooks/mercadopago',
    path: '/api/public/hooks/mercadopago',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDispatchOrdersRoute =
  ApiPublicHooksDispatchOrdersRouteImport.update({
    id: '/api/public/hooks/dispatch-orders',
    path: '/api/public/hooks/dispatch-orders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyHoroscopeRoute =
  ApiPublicHooksDailyHoroscopeRouteImport.update({
    id: '/api/public/hooks/daily-horoscope',
    path: '/api/public/hooks/daily-horoscope',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCrmFollowupsRoute =
  ApiPublicHooksCrmFollowupsRouteImport.update({
    id: '/api/public/hooks/crm-followups',
    path: '/api/public/hooks/crm-followups',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedPSlugCheckoutRoute =
  AuthenticatedPSlugCheckoutRouteImport.update({
    id: '/p/$slug/checkout',
    path: '/p/$slug/checkout',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ativacao': typeof AtivacaoRoute
  '/auth': typeof AuthRoute
  '/profissionais': typeof ProfissionaisRoute
  '/addons': typeof AuthenticatedAddonsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/horoscopo': typeof AuthenticatedHoroscopoRoute
  '/mapa-astral': typeof AuthenticatedMapaAstralRoute
  '/mapa-empresarial': typeof AuthenticatedMapaEmpresarialRoute
  '/meditacao': typeof AuthenticatedMeditacaoRoute
  '/numerologia': typeof AuthenticatedNumerologiaRoute
  '/numerologia-cabalistica': typeof AuthenticatedNumerologiaCabalisticaRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/oraculo': typeof AuthenticatedOraculoRoute
  '/pdf-css': typeof AuthenticatedPdfCssRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/tarot': typeof AuthenticatedTarotRoute
  '/api/chat': typeof ApiChatRoute
  '/p/$slug': typeof PSlugRoute
  '/r/$token': typeof RTokenRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/p/$slug/checkout': typeof AuthenticatedPSlugCheckoutRoute
  '/api/public/hooks/crm-followups': typeof ApiPublicHooksCrmFollowupsRoute
  '/api/public/hooks/daily-horoscope': typeof ApiPublicHooksDailyHoroscopeRoute
  '/api/public/hooks/dispatch-orders': typeof ApiPublicHooksDispatchOrdersRoute
  '/api/public/hooks/mercadopago': typeof ApiPublicHooksMercadopagoRoute
  '/api/public/manifest/icon': typeof ApiPublicManifestIconRoute
  '/api/public/manifest/webmanifest': typeof ApiPublicManifestWebmanifestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ativacao': typeof AtivacaoRoute
  '/auth': typeof AuthRoute
  '/profissionais': typeof ProfissionaisRoute
  '/addons': typeof AuthenticatedAddonsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/horoscopo': typeof AuthenticatedHoroscopoRoute
  '/mapa-astral': typeof AuthenticatedMapaAstralRoute
  '/mapa-empresarial': typeof AuthenticatedMapaEmpresarialRoute
  '/meditacao': typeof AuthenticatedMeditacaoRoute
  '/numerologia': typeof AuthenticatedNumerologiaRoute
  '/numerologia-cabalistica': typeof AuthenticatedNumerologiaCabalisticaRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/oraculo': typeof AuthenticatedOraculoRoute
  '/pdf-css': typeof AuthenticatedPdfCssRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/tarot': typeof AuthenticatedTarotRoute
  '/api/chat': typeof ApiChatRoute
  '/p/$slug': typeof PSlugRoute
  '/r/$token': typeof RTokenRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/p/$slug/checkout': typeof AuthenticatedPSlugCheckoutRoute
  '/api/public/hooks/crm-followups': typeof ApiPublicHooksCrmFollowupsRoute
  '/api/public/hooks/daily-horoscope': typeof ApiPublicHooksDailyHoroscopeRoute
  '/api/public/hooks/dispatch-orders': typeof ApiPublicHooksDispatchOrdersRoute
  '/api/public/hooks/mercadopago': typeof ApiPublicHooksMercadopagoRoute
  '/api/public/manifest/icon': typeof ApiPublicManifestIconRoute
  '/api/public/manifest/webmanifest': typeof ApiPublicManifestWebmanifestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/ativacao': typeof AtivacaoRoute
  '/auth': typeof AuthRoute
  '/profissionais': typeof ProfissionaisRoute
  '/_authenticated/addons': typeof AuthenticatedAddonsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/horoscopo': typeof AuthenticatedHoroscopoRoute
  '/_authenticated/mapa-astral': typeof AuthenticatedMapaAstralRoute
  '/_authenticated/mapa-empresarial': typeof AuthenticatedMapaEmpresarialRoute
  '/_authenticated/meditacao': typeof AuthenticatedMeditacaoRoute
  '/_authenticated/numerologia': typeof AuthenticatedNumerologiaRoute
  '/_authenticated/numerologia-cabalistica': typeof AuthenticatedNumerologiaCabalisticaRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/oraculo': typeof AuthenticatedOraculoRoute
  '/_authenticated/pdf-css': typeof AuthenticatedPdfCssRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/tarot': typeof AuthenticatedTarotRoute
  '/api/chat': typeof ApiChatRoute
  '/p/$slug': typeof PSlugRoute
  '/r/$token': typeof RTokenRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/p/$slug/checkout': typeof AuthenticatedPSlugCheckoutRoute
  '/api/public/hooks/crm-followups': typeof ApiPublicHooksCrmFollowupsRoute
  '/api/public/hooks/daily-horoscope': typeof ApiPublicHooksDailyHoroscopeRoute
  '/api/public/hooks/dispatch-orders': typeof ApiPublicHooksDispatchOrdersRoute
  '/api/public/hooks/mercadopago': typeof ApiPublicHooksMercadopagoRoute
  '/api/public/manifest/icon': typeof ApiPublicManifestIconRoute
  '/api/public/manifest/webmanifest': typeof ApiPublicManifestWebmanifestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ativacao'
    | '/auth'
    | '/profissionais'
    | '/addons'
    | '/admin'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/horoscopo'
    | '/mapa-astral'
    | '/mapa-empresarial'
    | '/meditacao'
    | '/numerologia'
    | '/numerologia-cabalistica'
    | '/onboarding'
    | '/oraculo'
    | '/pdf-css'
    | '/relatorios'
    | '/tarot'
    | '/api/chat'
    | '/p/$slug'
    | '/r/$token'
    | '/admin/logs'
    | '/p/$slug/checkout'
    | '/api/public/hooks/crm-followups'
    | '/api/public/hooks/daily-horoscope'
    | '/api/public/hooks/dispatch-orders'
    | '/api/public/hooks/mercadopago'
    | '/api/public/manifest/icon'
    | '/api/public/manifest/webmanifest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ativacao'
    | '/auth'
    | '/profissionais'
    | '/addons'
    | '/admin'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/horoscopo'
    | '/mapa-astral'
    | '/mapa-empresarial'
    | '/meditacao'
    | '/numerologia'
    | '/numerologia-cabalistica'
    | '/onboarding'
    | '/oraculo'
    | '/pdf-css'
    | '/relatorios'
    | '/tarot'
    | '/api/chat'
    | '/p/$slug'
    | '/r/$token'
    | '/admin/logs'
    | '/p/$slug/checkout'
    | '/api/public/hooks/crm-followups'
    | '/api/public/hooks/daily-horoscope'
    | '/api/public/hooks/dispatch-orders'
    | '/api/public/hooks/mercadopago'
    | '/api/public/manifest/icon'
    | '/api/public/manifest/webmanifest'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/ativacao'
    | '/auth'
    | '/profissionais'
    | '/_authenticated/addons'
    | '/_authenticated/admin'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/horoscopo'
    | '/_authenticated/mapa-astral'
    | '/_authenticated/mapa-empresarial'
    | '/_authenticated/meditacao'
    | '/_authenticated/numerologia'
    | '/_authenticated/numerologia-cabalistica'
    | '/_authenticated/onboarding'
    | '/_authenticated/oraculo'
    | '/_authenticated/pdf-css'
    | '/_authenticated/relatorios'
    | '/_authenticated/tarot'
    | '/api/chat'
    | '/p/$slug'
    | '/r/$token'
    | '/_authenticated/admin/logs'
    | '/_authenticated/p/$slug/checkout'
    | '/api/public/hooks/crm-followups'
    | '/api/public/hooks/daily-horoscope'
    | '/api/public/hooks/dispatch-orders'
    | '/api/public/hooks/mercadopago'
    | '/api/public/manifest/icon'
    | '/api/public/manifest/webmanifest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AtivacaoRoute: typeof AtivacaoRoute
  AuthRoute: typeof AuthRoute
  ProfissionaisRoute: typeof ProfissionaisRoute
  ApiChatRoute: typeof ApiChatRoute
  PSlugRoute: typeof PSlugRoute
  RTokenRoute: typeof RTokenRoute
  ApiPublicHooksCrmFollowupsRoute: typeof ApiPublicHooksCrmFollowupsRoute
  ApiPublicHooksDailyHoroscopeRoute: typeof ApiPublicHooksDailyHoroscopeRoute
  ApiPublicHooksDispatchOrdersRoute: typeof ApiPublicHooksDispatchOrdersRoute
  ApiPublicHooksMercadopagoRoute: typeof ApiPublicHooksMercadopagoRoute
  ApiPublicManifestIconRoute: typeof ApiPublicManifestIconRoute
  ApiPublicManifestWebmanifestRoute: typeof ApiPublicManifestWebmanifestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profissionais': {
      id: '/profissionais'
      path: '/profissionais'
      fullPath: '/profissionais'
      preLoaderRoute: typeof ProfissionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativacao': {
      id: '/ativacao'
      path: '/ativacao'
      fullPath: '/ativacao'
      preLoaderRoute: typeof AtivacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tarot': {
      id: '/_authenticated/tarot'
      path: '/tarot'
      fullPath: '/tarot'
      preLoaderRoute: typeof AuthenticatedTarotRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pdf-css': {
      id: '/_authenticated/pdf-css'
      path: '/pdf-css'
      fullPath: '/pdf-css'
      preLoaderRoute: typeof AuthenticatedPdfCssRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/oraculo': {
      id: '/_authenticated/oraculo'
      path: '/oraculo'
      fullPath: '/oraculo'
      preLoaderRoute: typeof AuthenticatedOraculoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/numerologia-cabalistica': {
      id: '/_authenticated/numerologia-cabalistica'
      path: '/numerologia-cabalistica'
      fullPath: '/numerologia-cabalistica'
      preLoaderRoute: typeof AuthenticatedNumerologiaCabalisticaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/numerologia': {
      id: '/_authenticated/numerologia'
      path: '/numerologia'
      fullPath: '/numerologia'
      preLoaderRoute: typeof AuthenticatedNumerologiaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meditacao': {
      id: '/_authenticated/meditacao'
      path: '/meditacao'
      fullPath: '/meditacao'
      preLoaderRoute: typeof AuthenticatedMeditacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mapa-empresarial': {
      id: '/_authenticated/mapa-empresarial'
      path: '/mapa-empresarial'
      fullPath: '/mapa-empresarial'
      preLoaderRoute: typeof AuthenticatedMapaEmpresarialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mapa-astral': {
      id: '/_authenticated/mapa-astral'
      path: '/mapa-astral'
      fullPath: '/mapa-astral'
      preLoaderRoute: typeof AuthenticatedMapaAstralRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/horoscopo': {
      id: '/_authenticated/horoscopo'
      path: '/horoscopo'
      fullPath: '/horoscopo'
      preLoaderRoute: typeof AuthenticatedHoroscopoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/addons': {
      id: '/_authenticated/addons'
      path: '/addons'
      fullPath: '/addons'
      preLoaderRoute: typeof AuthenticatedAddonsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/manifest/webmanifest': {
      id: '/api/public/manifest/webmanifest'
      path: '/api/public/manifest/webmanifest'
      fullPath: '/api/public/manifest/webmanifest'
      preLoaderRoute: typeof ApiPublicManifestWebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/manifest/icon': {
      id: '/api/public/manifest/icon'
      path: '/api/public/manifest/icon'
      fullPath: '/api/public/manifest/icon'
      preLoaderRoute: typeof ApiPublicManifestIconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/mercadopago': {
      id: '/api/public/hooks/mercadopago'
      path: '/api/public/hooks/mercadopago'
      fullPath: '/api/public/hooks/mercadopago'
      preLoaderRoute: typeof ApiPublicHooksMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-orders': {
      id: '/api/public/hooks/dispatch-orders'
      path: '/api/public/hooks/dispatch-orders'
      fullPath: '/api/public/hooks/dispatch-orders'
      preLoaderRoute: typeof ApiPublicHooksDispatchOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-horoscope': {
      id: '/api/public/hooks/daily-horoscope'
      path: '/api/public/hooks/daily-horoscope'
      fullPath: '/api/public/hooks/daily-horoscope'
      preLoaderRoute: typeof ApiPublicHooksDailyHoroscopeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/crm-followups': {
      id: '/api/public/hooks/crm-followups'
      path: '/api/public/hooks/crm-followups'
      fullPath: '/api/public/hooks/crm-followups'
      preLoaderRoute: typeof ApiPublicHooksCrmFollowupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/p/$slug/checkout': {
      id: '/_authenticated/p/$slug/checkout'
      path: '/p/$slug/checkout'
      fullPath: '/p/$slug/checkout'
      preLoaderRoute: typeof AuthenticatedPSlugCheckoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAddonsRoute: typeof AuthenticatedAddonsRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHoroscopoRoute: typeof AuthenticatedHoroscopoRoute
  AuthenticatedMapaAstralRoute: typeof AuthenticatedMapaAstralRoute
  AuthenticatedMapaEmpresarialRoute: typeof AuthenticatedMapaEmpresarialRoute
  AuthenticatedMeditacaoRoute: typeof AuthenticatedMeditacaoRoute
  AuthenticatedNumerologiaRoute: typeof AuthenticatedNumerologiaRoute
  AuthenticatedNumerologiaCabalisticaRoute: typeof AuthenticatedNumerologiaCabalisticaRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOraculoRoute: typeof AuthenticatedOraculoRoute
  AuthenticatedPdfCssRoute: typeof AuthenticatedPdfCssRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedTarotRoute: typeof AuthenticatedTarotRoute
  AuthenticatedPSlugCheckoutRoute: typeof AuthenticatedPSlugCheckoutRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAddonsRoute: AuthenticatedAddonsRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHoroscopoRoute: AuthenticatedHoroscopoRoute,
  AuthenticatedMapaAstralRoute: AuthenticatedMapaAstralRoute,
  AuthenticatedMapaEmpresarialRoute: AuthenticatedMapaEmpresarialRoute,
  AuthenticatedMeditacaoRoute: AuthenticatedMeditacaoRoute,
  AuthenticatedNumerologiaRoute: AuthenticatedNumerologiaRoute,
  AuthenticatedNumerologiaCabalisticaRoute:
    AuthenticatedNumerologiaCabalisticaRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOraculoRoute: AuthenticatedOraculoRoute,
  AuthenticatedPdfCssRoute: AuthenticatedPdfCssRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedTarotRoute: AuthenticatedTarotRoute,
  AuthenticatedPSlugCheckoutRoute: AuthenticatedPSlugCheckoutRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AtivacaoRoute: AtivacaoRoute,
  AuthRoute: AuthRoute,
  ProfissionaisRoute: ProfissionaisRoute,
  ApiChatRoute: ApiChatRoute,
  PSlugRoute: PSlugRoute,
  RTokenRoute: RTokenRoute,
  ApiPublicHooksCrmFollowupsRoute: ApiPublicHooksCrmFollowupsRoute,
  ApiPublicHooksDailyHoroscopeRoute: ApiPublicHooksDailyHoroscopeRoute,
  ApiPublicHooksDispatchOrdersRoute: ApiPublicHooksDispatchOrdersRoute,
  ApiPublicHooksMercadopagoRoute: ApiPublicHooksMercadopagoRoute,
  ApiPublicManifestIconRoute: ApiPublicManifestIconRoute,
  ApiPublicManifestWebmanifestRoute: ApiPublicManifestWebmanifestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
